@Library('pipelineLib') _

pipeline {
    agent any

    options {
        skipDefaultCheckout()
    }

    stages {
        stage('Stop running builds for the branch') {
            steps {
                stopRunningBuilds()
            }
        }

        stage('Wipe workspace and checkout') {
            steps {
                checkoutCurrentBranch()
            }
        }

        stage('Analyze') {
            steps {
                runWithMaven {
                    withChecks('Analyze checkstyle') {
                        runCheckstyle()
                    }

                    withChecks('Run tests') {
                        sh "mvn clean test"
                    }
                }
            }
        }
    }
}