@Library('pipelineLib') _

pipeline {
    agent any

    options {
        skipDefaultCheckout()
    }

    stages {
        stage('Stop running builds for the branch') {
            steps {
                stopRunningBuilds()
            }
        }

        stage('Wipe workspace and checkout') {
            steps {
                checkoutCurrentBranch()
            }
        }

        stage('Test and report') {
            steps {
                withMaven(
                        maven: 'maven-3',
                        options: [
                                findbugsPublisher(disabled: true),
                                jgivenPublisher(disabled: true),
                        ]
                ) {
                    sh "mvn test"
                }
            }
        }
    }
}