@Library('pipelineLib') _

pipeline {
    agent any

    options {
        skipDefaultCheckout()
    }

    stages {
        stage('Checkout') {
            steps {
                checkoutCurrentBranch()
                echo gitUtils.getCurrentBranch()
            }
        }
    }
}